import bpy
context = bpy.context
obj = context.object

namelist = [

# DAZ Genesis3
("pelvis", "ValveBiped.Bip01_Pelvis"),
("lThighBend", "ValveBiped.Bip01_L_Thigh"),
("lShin", "ValveBiped.Bip01_L_Calf"),
("lFoot", "ValveBiped.Bip01_L_Foot"),
("lMetatarsals", "ValveBiped.Bip01_L_Toe0"),
("rThighBend", "ValveBiped.Bip01_R_Thigh"),
("rShin", "ValveBiped.Bip01_R_Calf"),
("rFoot", "ValveBiped.Bip01_R_Foot"),
("rMetatarsals", "ValveBiped.Bip01_R_Toe0"),
("abdomenLower", "ValveBiped.Bip01_Spine"),
("abdomenUpper", "ValveBiped.Bip01_Spine1"),
("chestLower", "ValveBiped.Bip01_Spine2"),
("chestUpper", "ValveBiped.Bip01_Spine4"),
("neckLower", "ValveBiped.Bip01_Neck1"),
("head", "ValveBiped.Bip01_Head1"),
("lCollar", "ValveBiped.Bip01_L_Clavicle"),
("lShldrBend", "ValveBiped.Bip01_L_UpperArm"),
("lForearmBend", "ValveBiped.Bip01_L_Forearm"),
("lHand", "ValveBiped.Bip01_L_Hand"),
("lThumb1", "ValveBiped.Bip01_L_Finger0"),
("lThumb2", "ValveBiped.Bip01_L_Finger01"),
("lThumb3", "ValveBiped.Bip01_L_Finger02"),
("lIndex1", "ValveBiped.Bip01_L_Finger1"),
("lIndex2", "ValveBiped.Bip01_L_Finger11"),
("lIndex3", "ValveBiped.Bip01_L_Finger12"),
("lMid1", "ValveBiped.Bip01_L_Finger2"),
("lMid2", "ValveBiped.Bip01_L_Finger21"),
("lMid3", "ValveBiped.Bip01_L_Finger22"),
("lRing1", "ValveBiped.Bip01_L_Finger3"),
("lRing2", "ValveBiped.Bip01_L_Finger31"),
("lRing3", "ValveBiped.Bip01_L_Finger32"),
("lPinky1", "ValveBiped.Bip01_L_Finger4"),
("lPinky2", "ValveBiped.Bip01_L_Finger41"),
("lPinky3", "ValveBiped.Bip01_L_Finger42"),
("rCollar", "ValveBiped.Bip01_R_Clavicle"),
("rShldrBend", "ValveBiped.Bip01_R_UpperArm"),
("rForearmBend", "ValveBiped.Bip01_R_Forearm"),
("rHand", "ValveBiped.Bip01_R_Hand"),
("rThumb1", "ValveBiped.Bip01_R_Finger0"),
("rThumb2", "ValveBiped.Bip01_R_Finger01"),
("rThumb3", "ValveBiped.Bip01_R_Finger02"),
("rIndex1", "ValveBiped.Bip01_R_Finger1"),
("rIndex2", "ValveBiped.Bip01_R_Finger11"),
("rIndex3", "ValveBiped.Bip01_R_Finger12"),
("rMid1", "ValveBiped.Bip01_R_Finger2"),
("rMid2", "ValveBiped.Bip01_R_Finger21"),
("rMid3", "ValveBiped.Bip01_R_Finger22"),
("rRing1", "ValveBiped.Bip01_R_Finger3"),
("rRing2", "ValveBiped.Bip01_R_Finger31"),
("rRing3", "ValveBiped.Bip01_R_Finger32"),
("rPinky1", "ValveBiped.Bip01_R_Finger4"),
("rPinky2", "ValveBiped.Bip01_R_Finger41"),
("rPinky3", "ValveBiped.Bip01_R_Finger42"),

# Xnalara Exports (2 Spine)
("spine upper", "ValveBiped.Bip01_Spine2"),
("head neck lower", "ValveBiped.Bip01_Neck1"),
("head neck upper", "ValveBiped.Bip01_Head1"),

("pelvis", "ValveBiped.Bip01_Pelvis"),
("leg left thigh", "ValveBiped.Bip01_L_Thigh"),
("leg left knee", "ValveBiped.Bip01_L_Calf"),
("leg left ankle", "ValveBiped.Bip01_L_Foot"),
("leg left toes", "ValveBiped.Bip01_L_Toe0"),
("leg left toe", "ValveBiped.Bip01_L_Toe0"),
("leg right thigh", "ValveBiped.Bip01_R_Thigh"),
("leg right knee", "ValveBiped.Bip01_R_Calf"),
("leg right ankle", "ValveBiped.Bip01_R_Foot"),
("leg right toes", "ValveBiped.Bip01_R_Toe0"),
("leg right toe", "ValveBiped.Bip01_R_Toe0"),
("spine lower", "ValveBiped.Bip01_Spine1"),

("arm left shoulder 1", "ValveBiped.Bip01_L_Clavicle"),
("arm left shoulder 2", "ValveBiped.Bip01_L_UpperArm"),
("arm left elbow", "ValveBiped.Bip01_L_Forearm"),
("arm left wrist", "ValveBiped.Bip01_L_Hand"),
("arm left finger 1a", "ValveBiped.Bip01_L_Finger0"),
("arm left finger 1b", "ValveBiped.Bip01_L_Finger01"),
("arm left finger 1c", "ValveBiped.Bip01_L_Finger02"),
("arm left finger 2a", "ValveBiped.Bip01_L_Finger1"),
("arm left finger 2b", "ValveBiped.Bip01_L_Finger11"),
("arm left finger 2c", "ValveBiped.Bip01_L_Finger12"),
("arm left finger 3a", "ValveBiped.Bip01_L_Finger2"),
("arm left finger 3b", "ValveBiped.Bip01_L_Finger21"),
("arm left finger 3c", "ValveBiped.Bip01_L_Finger22"),
("arm left finger 4a", "ValveBiped.Bip01_L_Finger3"),
("arm left finger 4b", "ValveBiped.Bip01_L_Finger31"),
("arm left finger 4c", "ValveBiped.Bip01_L_Finger32"),
("arm left finger 5a", "ValveBiped.Bip01_L_Finger4"),
("arm left finger 5b", "ValveBiped.Bip01_L_Finger41"),
("arm left finger 5c", "ValveBiped.Bip01_L_Finger42"),
("arm right shoulder 1", "ValveBiped.Bip01_R_Clavicle"),
("arm right shoulder 2", "ValveBiped.Bip01_R_UpperArm"),
("arm right elbow", "ValveBiped.Bip01_R_Forearm"),
("arm right wrist", "ValveBiped.Bip01_R_Hand"),
("arm right finger 1a", "ValveBiped.Bip01_R_Finger0"),
("arm right finger 1b", "ValveBiped.Bip01_R_Finger01"),
("arm right finger 1c", "ValveBiped.Bip01_R_Finger02"),
("rIndex1", "ValveBiped.Bip01_R_Finger1"),
("rIndex2", "ValveBiped.Bip01_R_Finger11"),
("rIndex3", "ValveBiped.Bip01_R_Finger12"),
("arm right finger 2a", "ValveBiped.Bip01_R_Finger2"),
("arm right finger 2b", "ValveBiped.Bip01_R_Finger21"),
("arm right finger 2c", "ValveBiped.Bip01_R_Finger22"),
("arm right finger 3a", "ValveBiped.Bip01_R_Finger3"),
("arm right finger 3b", "ValveBiped.Bip01_R_Finger31"),
("arm right finger 3c", "ValveBiped.Bip01_R_Finger32"),
("arm right finger 4a", "ValveBiped.Bip01_R_Finger4"),
("arm right finger 4b", "ValveBiped.Bip01_R_Finger41"),
("arm right finger 4c", "ValveBiped.Bip01_R_Finger42"),

# uModel Exports
    
("Bip01-Pelvis", "ValveBiped.Bip01_Pelvis"),
("Bip01-L-Thigh", "ValveBiped.Bip01_L_Thigh"),
("Bip01-L-Calf", "ValveBiped.Bip01_L_Calf"),
("Bip01-L-Foot", "ValveBiped.Bip01_L_Foot"),
("Bip01-L-Toe0", "ValveBiped.Bip01_L_Toe0"),
("Bip01-R-Thigh", "ValveBiped.Bip01_R_Thigh"),
("Bip01-R-Calf", "ValveBiped.Bip01_R_Calf"),
("Bip01-R-Foot", "ValveBiped.Bip01_R_Foot"),
("Bip01-R-Toe0", "ValveBiped.Bip01_R_Toe0"),
("Bip01-Spine", "ValveBiped.Bip01_Spine"),
("Bip01-Spine1", "ValveBiped.Bip01_Spine1"),
("Bip01-Spine2", "ValveBiped.Bip01_Spine2"),
("Bip01-Spine3", "ValveBiped.Bip01_Spine4"),
("Bip01-Neck", "ValveBiped.Bip01_Neck1"),
("Bip01-Head", "ValveBiped.Bip01_Head1"),
("Bip01-L-Clavicle", "ValveBiped.Bip01_L_Clavicle"),
("Bip01-L-UpperArm", "ValveBiped.Bip01_L_UpperArm"),
("Bip01-L-Forearm", "ValveBiped.Bip01_L_Forearm"),
("Bip01-L-Hand", "ValveBiped.Bip01_L_Hand"),
("Bip01-L-Finger0", "ValveBiped.Bip01_L_Finger0"),
("Bip01-L-Finger01", "ValveBiped.Bip01_L_Finger01"),
("Bip01-L-Finger02", "ValveBiped.Bip01_L_Finger02"),
("Bip01-L-Finger1", "ValveBiped.Bip01_L_Finger1"),
("Bip01-L-Finger11", "ValveBiped.Bip01_L_Finger11"),
("Bip01-L-Finger12", "ValveBiped.Bip01_L_Finger12"),
("Bip01-L-Finger2", "ValveBiped.Bip01_L_Finger2"),
("Bip01-L-Finger21", "ValveBiped.Bip01_L_Finger21"),
("Bip01-L-Finger22", "ValveBiped.Bip01_L_Finger22"),
("Bip01-L-Finger3", "ValveBiped.Bip01_L_Finger3"),
("Bip01-L-Finger31", "ValveBiped.Bip01_L_Finger31"),
("Bip01-L-Finger32", "ValveBiped.Bip01_L_Finger32"),
("Bip01-L-Finger4", "ValveBiped.Bip01_L_Finger4"),
("Bip01-L-Finger41", "ValveBiped.Bip01_L_Finger41"),
("Bip01-L-Finger42", "ValveBiped.Bip01_L_Finger42"),
("Bip01-R-Clavicle", "ValveBiped.Bip01_R_Clavicle"),
("Bip01-R-UpperArm", "ValveBiped.Bip01_R_UpperArm"),
("Bip01-R-Forearm", "ValveBiped.Bip01_R_Forearm"),
("Bip01-R-Hand", "ValveBiped.Bip01_R_Hand"),
("Bip01-R-Finger0", "ValveBiped.Bip01_R_Finger0"),
("Bip01-R-Finger01", "ValveBiped.Bip01_R_Finger01"),
("Bip01-R-Finger02", "ValveBiped.Bip01_R_Finger02"),
("Bip01-R-Finger1", "ValveBiped.Bip01_R_Finger1"),
("Bip01-R-Finger11", "ValveBiped.Bip01_R_Finger11"),
("Bip01-R-Finger12", "ValveBiped.Bip01_R_Finger12"),
("Bip01-R-Finger2", "ValveBiped.Bip01_R_Finger2"),
("Bip01-R-Finger21", "ValveBiped.Bip01_R_Finger21"),
("Bip01-R-Finger22", "ValveBiped.Bip01_R_Finger22"),
("Bip01-R-Finger3", "ValveBiped.Bip01_R_Finger3"),
("Bip01-R-Finger31", "ValveBiped.Bip01_R_Finger31"),
("Bip01-R-Finger32", "ValveBiped.Bip01_R_Finger32"),
("Bip01-R-Finger4", "ValveBiped.Bip01_R_Finger4"),
("Bip01-R-Finger41", "ValveBiped.Bip01_R_Finger41"),
("Bip01-R-Finger42", "ValveBiped.Bip01_R_Finger42"),


# Dead or Alive Exports
    
("MOT00_Hips", "ValveBiped.Bip01_Pelvis"),
("MOT_*UpLeg.1.L", "ValveBiped.Bip01_L_Thigh"),
("MOT_*Leg.1.L", "ValveBiped.Bip01_L_Calf"),
("MOT_*Foot.1.L", "ValveBiped.Bip01_L_Foot"),
("MOT_*Toe.1.L", "ValveBiped.Bip01_L_Toe0"),
("MOT_*UpLeg.1.R", "ValveBiped.Bip01_R_Thigh"),
("MOT_*Leg.1.R", "ValveBiped.Bip01_R_Calf"),
("MOT_*Foot.1.R", "ValveBiped.Bip01_R_Foot"),
("MOT_*Toe.1.R", "ValveBiped.Bip01_R_Toe0"),
("MOT16_Waist", "ValveBiped.Bip01_Spine"),
("MOT02_Chest", "ValveBiped.Bip01_Spine1"),
("MOT15_Neck", "ValveBiped.Bip01_Neck1"),
("MOT01_Head", "ValveBiped.Bip01_Head1"),
("MOT_*Shoulder.1.L", "ValveBiped.Bip01_L_Clavicle"),
("MOT_*Arm.1.L", "ValveBiped.Bip01_L_UpperArm"),
("MOT_*ForeArm.1.L", "ValveBiped.Bip01_L_Forearm"),
("MOT_*Hand.1.L", "ValveBiped.Bip01_L_Hand"),
("OPT_Hand_*_Thumb1.1.L", "ValveBiped.Bip01_L_Finger0"),
("OPT_Hand_*_Thumb2.1.L", "ValveBiped.Bip01_L_Finger01"),
("OPT_Hand_*_Thumb3.1.L", "ValveBiped.Bip01_L_Finger02"),
("OPT_Hand_*_Index1.1.L", "ValveBiped.Bip01_L_Finger1"),
("OPT_Hand_*_Index2.1.L", "ValveBiped.Bip01_L_Finger11"),
("OPT_Hand_*_Index3.1.L", "ValveBiped.Bip01_L_Finger12"),
("OPT_Hand_*_Middle1.1.L", "ValveBiped.Bip01_L_Finger2"),
("OPT_Hand_*_Middle2.1.L", "ValveBiped.Bip01_L_Finger21"),
("OPT_Hand_*_Middle3.1.L", "ValveBiped.Bip01_L_Finger22"),
("OPT_Hand_*_Ring1.1.L", "ValveBiped.Bip01_L_Finger3"),
("OPT_Hand_*_Ring2.1.L", "ValveBiped.Bip01_L_Finger31"),
("OPT_Hand_*_Ring3.1.L", "ValveBiped.Bip01_L_Finger32"),
("OPT_Hand_*_Pinky1.1.L", "ValveBiped.Bip01_L_Finger4"),
("OPT_Hand_*_Pinky2.1.L", "ValveBiped.Bip01_L_Finger41"),
("OPT_Hand_*_Pinky3.1.L", "ValveBiped.Bip01_L_Finger42"),
("MOT_*Shoulder.1.R", "ValveBiped.Bip01_R_Clavicle"),
("MOT_*Arm.1.R", "ValveBiped.Bip01_R_UpperArm"),
("MOT_*ForeArm.1.R", "ValveBiped.Bip01_R_Forearm"),
("MOT_*Hand.1.R", "ValveBiped.Bip01_R_Hand"),
("OPT_Hand_*_Thumb1.1.R", "ValveBiped.Bip01_R_Finger0"),
("OPT_Hand_*_Thumb2.1.R", "ValveBiped.Bip01_R_Finger01"),
("OPT_Hand_*_Thumb3.1.R", "ValveBiped.Bip01_R_Finger02"),
("OPT_Hand_*_Index1.1.R", "ValveBiped.Bip01_R_Finger1"),
("OPT_Hand_*_Index2.1.R", "ValveBiped.Bip01_R_Finger11"),
("OPT_Hand_*_Index3.1.R", "ValveBiped.Bip01_R_Finger12"),
("OPT_Hand_*_Middle1.1.R", "ValveBiped.Bip01_R_Finger2"),
("OPT_Hand_*_Middle2.1.R", "ValveBiped.Bip01_R_Finger21"),
("OPT_Hand_*_Middle3.1.R", "ValveBiped.Bip01_R_Finger22"),
("OPT_Hand_*_Ring1.1.R", "ValveBiped.Bip01_R_Finger3"),
("OPT_Hand_*_Ring2.1.R", "ValveBiped.Bip01_R_Finger31"),
("OPT_Hand_*_Ring3.1.R", "ValveBiped.Bip01_R_Finger32"),
("OPT_Hand_*_Pinky1.1.R", "ValveBiped.Bip01_R_Finger4"),
("OPT_Hand_*_Pinky2.1.R", "ValveBiped.Bip01_R_Finger41"),
("OPT_Hand_*_Pinky3.1.R", "ValveBiped.Bip01_R_Finger42"),


("OPT_AS_*_Hip.0.L", "butt left"),
("OPT_AS_*_Hip.0.R", "butt right"),
("OPT_Breast_*_base.1.L", "breast left"),
("OPT_Breast_*_tip.1.L", "breast left tip"),
("OPT_Breast_*_base.1.R", "breast right"),
("OPT_Breast_*_tip.1.R", "breast right tip"),


#Smite xnalara ports
("Pelvis", "ValveBiped.Bip01_Pelvis"),
("L Thigh", "ValveBiped.Bip01_L_Thigh"),
("L Calf", "ValveBiped.Bip01_L_Calf"),
("L Foot", "ValveBiped.Bip01_L_Foot"),
("L Toe0", "ValveBiped.Bip01_L_Toe0"),
("R Thigh", "ValveBiped.Bip01_R_Thigh"),
("R Calf", "ValveBiped.Bip01_R_Calf"),
("R Foot", "ValveBiped.Bip01_R_Foot"),
("R Toe0", "ValveBiped.Bip01_R_Toe0"),
("Spine", "ValveBiped.Bip01_Spine"),
("Spine1", "ValveBiped.Bip01_Spine1"),
("Spine2", "ValveBiped.Bip01_Spine2"),
("Neck", "ValveBiped.Bip01_Neck1"),
("Head", "ValveBiped.Bip01_Head1"),
("L Clavicle", "ValveBiped.Bip01_L_Clavicle"),
("L UpperArm", "ValveBiped.Bip01_L_UpperArm"),
("L Forearm", "ValveBiped.Bip01_L_Forearm"),
("L Hand", "ValveBiped.Bip01_L_Hand"),
("L Finger0", "ValveBiped.Bip01_L_Finger0"),
("L Finger01", "ValveBiped.Bip01_L_Finger01"),
("L Finger02", "ValveBiped.Bip01_L_Finger02"),
("L Finger1", "ValveBiped.Bip01_L_Finger1"),
("L Finger11", "ValveBiped.Bip01_L_Finger11"),
("L Finger12", "ValveBiped.Bip01_L_Finger12"),
("L Finger2", "ValveBiped.Bip01_L_Finger2"),
("L Finger21", "ValveBiped.Bip01_L_Finger21"),
("L Finger22", "ValveBiped.Bip01_L_Finger22"),
("L Finger3", "ValveBiped.Bip01_L_Finger3"),
("L Finger31", "ValveBiped.Bip01_L_Finger31"),
("L Finger32", "ValveBiped.Bip01_L_Finger32"),
("L Finger4", "ValveBiped.Bip01_L_Finger4"),
("L Finger41", "ValveBiped.Bip01_L_Finger41"),
("L Finger42", "ValveBiped.Bip01_L_Finger42"),
("R Clavicle", "ValveBiped.Bip01_R_Clavicle"),
("R UpperArm", "ValveBiped.Bip01_R_UpperArm"),
("R Forearm", "ValveBiped.Bip01_R_Forearm"),
("R Hand", "ValveBiped.Bip01_R_Hand"),
("R Finger0", "ValveBiped.Bip01_R_Finger0"),
("R Finger01", "ValveBiped.Bip01_R_Finger01"),
("R Finger02", "ValveBiped.Bip01_R_Finger02"),
("R Finger1", "ValveBiped.Bip01_R_Finger1"),
("R Finger11", "ValveBiped.Bip01_R_Finger11"),
("R Finger12", "ValveBiped.Bip01_R_Finger12"),
("R Finger2", "ValveBiped.Bip01_R_Finger2"),
("R Finger21", "ValveBiped.Bip01_R_Finger21"),
("R Finger22", "ValveBiped.Bip01_R_Finger22"),
("R Finger3", "ValveBiped.Bip01_R_Finger3"),
("R Finger31", "ValveBiped.Bip01_R_Finger31"),
("R Finger32", "ValveBiped.Bip01_R_Finger32"),
("R Finger4", "ValveBiped.Bip01_R_Finger4"),
("R Finger41", "ValveBiped.Bip01_R_Finger41"),
("R Finger42", "ValveBiped.Bip01_R_Finger42"),

# Dynasty Warriors Exports

("jnt_012", "ValveBiped.Bip01_Spine4"),
("jnt_013", "ValveBiped.Bip01_Neck1"),
("jnt_014", "ValveBiped.Bip01_Head1"),    
("jnt_094", "head eyeball left"),
("jnt_095", "head eyeball right"),
("jnt_100", "head eyebrow left 1"),
("jnt_102", "head eyebrow left 2"),
("jnt_101", "head eyebrow right 1"),
("jnt_103", "head eyebrow right 2"),
("jnt_096", "head eyelid left upper"),
("jnt_098", "head eyelid left lower"),
("jnt_097", "head eyelid right upper"),
("jnt_099", "head eyelid right lower"),
("jnt_104", "head cheek left 1"),
("jnt_105", "head cheek right 1"),
("jnt_112", "head jaw"),
("jnt_106", "head lip upper left 1"),
("jnt_108", "head lip upper left 2"),
("jnt_107", "head lip upper right 1"),
("jnt_109", "head lip upper right 2"),
("jnt_110", "head lip lower left"),
("jnt_111", "head lip lower right"),
("jnt_113", "head lip lower middle"),

#custom
("arm left finger thumb a", "ValveBiped.Bip01_L_Finger0"),
("arm left finger thumb b", "ValveBiped.Bip01_L_Finger01"),
("arm left finger thumb c", "ValveBiped.Bip01_L_Finger02"),
("arm left finger index a", "ValveBiped.Bip01_L_Finger1"),
("arm left finger index b", "ValveBiped.Bip01_L_Finger11"),
("arm left finger index c", "ValveBiped.Bip01_L_Finger12"),
("arm left finger index c", "ValveBiped.Bip01_L_Finger12"),
("arm left finger middle a", "ValveBiped.Bip01_L_Finger2"),
("arm left finger middle b", "ValveBiped.Bip01_L_Finger21"),
("arm left finger middle c", "ValveBiped.Bip01_L_Finger22"),
("arm left finger ring a", "ValveBiped.Bip01_L_Finger3"),
("arm left finger ring b", "ValveBiped.Bip01_L_Finger31"),
("arm left finger ring c", "ValveBiped.Bip01_L_Finger32"),
("arm left finger pinky a", "ValveBiped.Bip01_L_Finger4"),
("arm left finger pinky b", "ValveBiped.Bip01_L_Finger41"),
("arm left finger pinky c", "ValveBiped.Bip01_L_Finger42"),
("arm right finger thumb a", "VaRveBiped.Bip01_R_Finger0"),
("arm right finger thumb b", "VaRveBiped.Bip01_R_Finger01"),
("arm right finger thumb c", "VaRveBiped.Bip01_R_Finger02"),
("arm right finger index a", "VaRveBiped.Bip01_R_Finger1"),
("arm right finger index b", "VaRveBiped.Bip01_R_Finger11"),
("arm right finger index c", "VaRveBiped.Bip01_R_Finger12"),
("arm right finger index c", "VaRveBiped.Bip01_R_Finger12"),
("arm right finger middRe a", "VaRveBiped.Bip01_R_Finger2"),
("arm right finger middRe b", "VaRveBiped.Bip01_R_Finger21"),
("arm right finger middRe c", "VaRveBiped.Bip01_R_Finger22"),
("arm right finger ring a", "VaRveBiped.Bip01_R_Finger3"),
("arm right finger ring b", "VaRveBiped.Bip01_R_Finger31"),
("arm right finger ring c", "VaRveBiped.Bip01_R_Finger32"),
("arm right finger pinky a", "VaRveBiped.Bip01_R_Finger4"),
("arm right finger pinky b", "VaRveBiped.Bip01_R_Finger41"),
("arm right finger pinky c", "VaRveBiped.Bip01_R_Finger42")

]

for name, newname in namelist:
    # get the pose bone with name
    pb = obj.pose.bones.get(name)
    # continue if no bone of that name
    if pb is None:
        continue
    # rename
    pb.name = newname